# Generated by Django 5.2.1 on 2025-05-23 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
